config/routes.rb
  Rails.application.routes.draw do
    get "uploads/new"
    get "uploads/create"
    root "vendas#index"
    get 'vendas/show_all', to: 'vendas#show_all', as: 'show_vendas'
    get 'vendas/export_pdf', to: 'vendas#export_pdf', as: 'export_vendas_pdf'
    resources :vendas do 
      collection do
        get :export_csv
        get :export_pdf
      end
    end
    resources :produtos, only: [:create] 
    resources :uploads, only: [:new, :create]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/produto.rb
class Produto < ApplicationRecord
    has_many :venda_produtos
    has_many :vendas, through: :venda_produtos
  
    validates :nome, presence: true
    validates :preco, presence: true, numericality: { greater_than: 0 }
  end  

app/models/upload.rb
class Upload < ApplicationRecord
    mount_uploader :file, FileUploader
  
    # Processa o arquivo CSV e cria produtos
    def process_csv
      return unless file.present?
  
      # Abre o arquivo CSV e lê linha por linha
      CSV.foreach(file.path, headers: true) do |row|
        Produto.create!(
          nome: row['nome'],
          preco: row['preco'].to_f
        )
      end
    end
end

app/models/venda.rb
class Venda < ApplicationRecord
    has_many :venda_produtos, dependent: :destroy
    has_many :produtos, through: :venda_produtos
  
    validates :cliente_nome, presence: true
    validates :cliente_cpf, presence: true, format: { with: /\A\d{11}\z/, message: "deve ter 11 dígitos" }
  end  

app/models/venda_produto.rb
class VendaProduto < ApplicationRecord
  belongs_to :venda
  belongs_to :produto

  validates :quantidade, presence: true, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
    def create
      @produto = Produto.new(produto_params)
      if @produto.save
        render json: { message: "Produto cadastrado com sucesso!", produto: @produto }
      else
        render json: { errors: @produto.errors.full_messages }, status: :unprocessable_entity
      end
    end
  
    private
  
    def produto_params
      params.require(:produto).permit(:nome, :preco)
    end
  end  

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.new(upload_params)

    if @upload.save
      @upload.process_csv
      redirect_to root_path, notice: "Produtos importados com sucesso!"
    else
      render :new
    end
  end

  private

  def upload_params
    params.require(:upload).permit(:file)
  end
end

app/controllers/vendas_controller.rb
class VendasController < ApplicationController
    require 'csv'
    before_action :set_venda, only: [:show, :edit, :update, :destroy]
  
    def index
    end
  
    def show_all
        @vendas = Venda.page(params[:page]).per(3)
    end
  
    def show
        @venda = Venda.find(params[:id])
    end

    def new
      @venda = Venda.new
      @produtos = Produto.all
    end
  
    def create
        @venda = Venda.new(venda_params)
      
        if @venda.save
          # Criando as relações VendaProduto para cada produto selecionado
          params[:produtos].each do |produto_id, _|
            quantidade = params[:quantidades][produto_id].to_i
            VendaProduto.create!(venda: @venda, produto_id: produto_id, quantidade: quantidade)
          end
      
          # Atualizando o total da venda
          @venda.update(total: calcular_total(@venda))
      
          redirect_to @venda
        else
          render :new
        end
    end   
  
    def edit
      @produtos = Produto.all
    end
  
    def update
      @venda.venda_produtos.destroy_all
      params[:produtos].each do |produto_id, _|
        quantidade = params[:quantidades][produto_id].to_i
        VendaProduto.create!(venda: @venda, produto_id: produto_id, quantidade: quantidade)
      end
      @venda.update(venda_params.merge(total: calcular_total(@venda)))
      redirect_to @venda
    end
    
    def destroy
      @venda.destroy
        respond_to do |format|
        format.html { redirect_to show_vendas_path, message: "Venda excluída com sucesso." }
        format.js   # Responde ao JavaScript se `remote: true` foi usado.
      end
    end       
  
    def export_pdf
      @vendas = Venda.all
    
      pdf = Prawn::Document.new
      pdf.text "Listagem de Vendas", size: 18, style: :bold
      pdf.move_down 20
    
      table_data = [["ID", "Cliente", "CPF", "Total"]] + 
                   @vendas.map do |venda|
                     [venda.id, venda.cliente_nome, venda.cliente_cpf, "R$ #{venda.total}"]
                   end
    
      pdf.table(table_data, header: true, width: 500) do
        row(0).font_style = :bold
        self.header = true
      end
    
      send_data pdf.render,
                filename: "vendas_listagem.pdf",
                type: "application/pdf",
                disposition: "inline"
    end

    def export_csv
      @vendas = Venda.all
      csv_data = CSV.generate(headers: true) do |csv|
        csv << ["ID", "Cliente", "CPF"] # Cabeçalho do CSV
        @vendas.each do |venda|
          csv << [venda.id, venda.cliente_nome, venda.cliente_cpf] # Dados de cada venda
        end
      end
  
      send_data csv_data,
                filename: "vendas_listagem.csv",
                type: "text/csv",
                disposition: "inline"
    end

    private
  
    def set_venda
      @venda = Venda.find(params[:id])
    end
  
    def venda_params
      params.require(:venda).permit(:cliente_nome, :cliente_cpf)
    end
  
    def calcular_total(venda)
      venda.venda_produtos.joins(:produto).sum("produtos.preco * venda_produtos.quantidade")
    end
    
  end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Mercadinho Cg" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/uploads/create.html.erb
<h1>Uploads#create</h1>
<p>Find me in app/views/uploads/create.html.erb</p>

app/views/uploads/new.html.erb
<h1>Importar Produtos</h1>

<%= form_with model: @upload, local: true do |f| %>
  <div class="field">
    <%= f.label :file, "Arquivo CSV" %>
    <%= f.file_field :file %>
  </div>

  <div class="actions">
    <%= f.submit "Importar" %>
  </div>
<% end %>

app/views/vendas/edit.html.erb
<h1>Editar Venda</h1>
<%= form_with model: @venda, url: venda_path(@venda), method: :patch, local: true do |form| %>
  <div>
    <%= form.label :cliente_nome, "Nome do Cliente" %>
    <%= form.text_field :cliente_nome, value: @venda.cliente_nome %>
  </div>
  <div>
    <%= form.label :cliente_cpf, "CPF do Cliente" %>
    <%= form.text_field :cliente_cpf, value: @venda.cliente_cpf %>
  </div>
  <h3>Produtos</h3>
  <% @produtos.each do |produto| %>
    <div>
      <%= check_box_tag "produtos[#{produto.id}]", 1, @venda.produtos.include?(produto) %>
      <%= label_tag "produtos_#{produto.id}", "#{produto.nome} - R$ #{produto.preco}" %>
      <%= number_field_tag "quantidades[#{produto.id}]", @venda.venda_produtos.find_by(produto: produto)&.quantidade || 1, min: 1 %>
    </div>
  <% end %>
  <div>
    <%= form.submit "Atualizar Venda" %>
  </div>
<% end %>

app/views/vendas/index.html.erb
<h1>Bem-Vindo ao Mercadinho CG</h1>
<div>
  <ul>
    <li>
      <a href="<%= new_venda_path %>" class="button">Criar Nova Venda</a>
    </li>
    <li>
      <a href="<%= show_vendas_path %>" class="button">Mostrar Vendas</a>
    </li>
    <li>
      <%= link_to 'Exportar para CSV', export_csv_vendas_path %>
    </li>
    <li> 
      <%= link_to "Upload de Produtos", new_upload_path, class: "btn btn-primary" %>
    </li>
  </ul>
</div>

app/views/vendas/new.html.erb
<h1>Criar Nova Venda</h1>
<%= form_with model: @venda, url: vendas_path, local: true do |form| %>
  <div>
    <%= form.label :cliente_nome, "Nome do Cliente" %>
    <%= form.text_field :cliente_nome %>
  </div>
  <div>
    <%= form.label :cliente_cpf, "CPF do Cliente" %>
    <%= form.text_field :cliente_cpf %>
  </div>

  <h3>Produtos</h3>
  <% @produtos.each do |produto| %>
    <div>
      <%= check_box_tag "produtos[#{produto.id}]", 1 %>
      <%= label_tag "produtos_#{produto.id}", "#{produto.nome} - R$ #{produto.preco}" %>
      <%= number_field_tag "quantidades[#{produto.id}]", 1, min: 1 %>
    </div>
  <% end %>

  <div>
    <%= form.submit "Criar Venda" %>
  </div>
<% end %>

app/views/vendas/show.html.erb
<h1>Detalhes da Venda</h1>

<% if notice %>
  <div class="alert alert-success">
    <strong><%= notice %></strong>
  </div>
<% end %>

<p><strong>Nome do Cliente:</strong> <%= @venda.cliente_nome %></p>
<p><strong>CPF do Cliente:</strong> <%= @venda.cliente_cpf %></p>
<p><strong>Total:</strong> R$ <%= @venda.total %></p>

<h3>Produtos</h3>
<table>
  <thead>
    <tr>
      <th>Produto</th>
      <th>Preço</th>
      <th>Quantidade</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @venda.venda_produtos.each do |venda_produto| %>
      <tr>
        <td><%= venda_produto.produto.nome %></td>
        <td>R$ <%= venda_produto.produto.preco %></td>
        <td><%= venda_produto.quantidade %></td>
        <td>R$ <%= venda_produto.produto.preco * venda_produto.quantidade %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Voltar para a lista de vendas', show_vendas_path %>
<%= link_to 'Voltar para a página inicial', root_path %>

app/views/vendas/show_all.html.erb
<h1>Vendas Cadastradas</h1>

<% if @vendas.any? %>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Cliente</th>
        <th>CPF</th>
        <th>Total</th>  
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @vendas.each do |venda| %>
        <tr data-venda-id="<%= venda.id %>">
           <td><%= venda.id %></td>
          <td><%= venda.cliente_nome %></td>
          <td><%= venda.cliente_cpf %></td>
          <td>R$ <%= venda.total %></td>
          <td>
            <a href="<%= venda_path(venda) %>">Detalhes</a>
            <a href="<%= edit_venda_path(venda) %>">Editar</a>
            <%= button_to "Excluir", venda_path(venda), method: :delete, form: {data: { turbo_confirm: "Tem certeza que deseja apagar a venda?" } } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="pagination">
    <%= paginate @vendas %> <!-- Link de paginação gerado pelo Kaminari -->
  </div>
<% else %>
  <p>Nenhuma venda cadastrada.</p>
<% end %>

<a href="<%= new_venda_path %>">Criar Nova Venda</a>  
<%= link_to 'Exportar PDF', export_pdf_vendas_path, target: "_blank" %>
<a href="<%= root_path %>">Voltar</a>